
[functions.compute-triage-features]
enabled = true
verify_jwt = true
import_map = "./functions/compute-triage-features/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/compute-triage-features/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/compute-triage-features/*.html" ]

[functions.compute-negotiation-features]
enabled = true
verify_jwt = true
import_map = "./functions/compute-negotiation-features/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/compute-negotiation-features/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/compute-negotiation-features/*.html" ]

[functions.compute-planning-features]
enabled = true
verify_jwt = true
import_map = "./functions/compute-planning-features/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/compute-planning-features/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/compute-planning-features/*.html" ]

[functions.finalize-run]
enabled = true
verify_jwt = true
import_map = "./functions/finalize-run/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/finalize-run/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/finalize-run/*.html" ]
